root_dir = "."

# UUID 的开始时间
start_time = "2020-07-01 00:00:00 +0000"

# 定义 HTTP 监听端口
[app]
name = ""
host = "http://localhost"
port = 7788
mode = "debug" # "debug" "release"
ver = "0.1"
default_page_size = 10

[jwt]
# jwt 设置默认的过期时间
expire_seconds = 604800 # 3600*24*7
secret = ""
# remember_me 的过期时间，duration
expire = "720h" # 24h*30天

# 日志配置
[log]
level = "insdsadfo"
filename = "./app.log"
max_size = 100
max_age = 30
max_backups = 7
compress = false

# 存储 MySQL 配置
[mysql]
driver = "mysql"
user = ""
password = ""
host = ""
port = ""
dbname = ""
charset = "utf8mb4"

prefix = "bt_"

max_idle = 2
max_conn = 10

[email]
smtp_username = ""
smtp_password = ""
smtp_host = ""
smtp_port = 25

[seo]
keywords = ""
description = ""

[upload]
save_path = "static/upload/"
img_max_size = 5000 # Kb Mb Gb
video_max_size = 50000

[wechat]
appid = ""
secret = ""

[ocr]
generalBasic = "https://aip.baidubce.com/rest/2.0/ocr/v1/general_basic"
apiKey = ""
secretKey = ""


[tts] # 百度语音技术
apiKey    = ""
secretKey = ""
# 发音人选择, 基础音库：0为度小美，1为度小宇，3为度逍遥，4为度丫丫，
# 精品音库：5为度小娇，103为度米朵，106为度博文，110为度小童，111为度小萌，默认为度小美
PER = 4
# 语速，取值0-15，默认为5中语速
SPD = 5
# 音调，取值0-15，默认为5中语调
PIT = 5
# 音量，取值0-9，默认为5中音量
VOL = 5
# 下载的文件格式, 3：mp3(default) 4： pcm-16k 5： pcm-8k 6. wav
AUE     = 3
CUID    = "123456PYTHON"
TTS_URL = "http://tsn.baidu.com/text2audio"
